### PR TITLE
Fix page count incorrect calculation on reupload PDF

### PR DESCRIPTION
**Pull request by acestronautical**
addresses https://github.com/momijizukamori/bookbinder-js/issues/71

### CODE REVIEW

**Review by sithel — APPROVED** [review]
🙌  
Thank you!

**Comment by sithel** [comment]
err-- could you bump the version number in `package.json` and then I'll land it

**Comment by sithel** [comment]
(or you can if you've permissions?)

**Comment by acestronautical** [comment]
I bumped the version to 1.3.2, was that what you were requesting?

**Pull request merged**
